fax:
  check_interval: 600  # 10分
  file_extensions: [".tif", ".tiff"]
  
ocr:
  retry_count: 3
  retry_delay: 2  # 秒
  confidence_threshold: 0.7
  max_retries: 30  # カスタムAPI用
  retry_interval: 10  # カスタムAPI用（秒）
  
mail:
  subject_template: "FAX受信通知 - {filename}"
  retry_count: 3
  
logging:
  max_bytes: 10485760  # 10MB
  backup_count: 5
  
processing:
  max_concurrent_files: 3
  temp_file_cleanup: true